apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-c7w5
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-dxga-tenant/rhtap-demo-app/hacbs-test-project-c7w5@sha256:3d19ea27913c585ee179048ae12cd3343fbe21b8105282ec908e7ab5246cb287
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
